##################################
#    FOR EXAMPLE  ROUTING YAML   #
##################################

###  DOCUMENTATION  ###
documentation:
  pattern:     /documentation
  defaults: {"controller": "demoBundle:demo:readme"}
